import { PrismaService } from 'prisma/prisma.service';

export async function seedDrugCatalog(prisma: PrismaService): Promise<void> {
    const categories = await prisma.allergenCategory.findMany();
    const categoryMap = new Map(categories.map((c) => [c.categoryCode, c.categoryId]));

    const drugs = [
        // Kháng sinh
        {
            drugCode: 'AMOX500',
            drugName: 'Amoxicillin 500mg',
            genericName: 'Amoxicillin',
            strength: '500mg',
            dosageForm: 'viên nang',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Kháng sinh',
            allergenCategoryCode: 'PENICILLIN',
            price: 2500,
        },
        {
            drugCode: 'AUGM625',
            drugName: 'Augmentin 625mg',
            genericName: 'Amoxicillin/Clavulanate',
            strength: '625mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Kháng sinh',
            allergenCategoryCode: 'PENICILLIN',
            price: 8500,
        },
        {
            drugCode: 'CEPH500',
            drugName: 'Cephalexin 500mg',
            genericName: 'Cephalexin',
            strength: '500mg',
            dosageForm: 'viên nang',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Kháng sinh',
            allergenCategoryCode: null,
            price: 3000,
        },
        {
            drugCode: 'BACTRIM480',
            drugName: 'Bactrim 480mg',
            genericName: 'Sulfamethoxazole/Trimethoprim',
            strength: '480mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Kháng sinh',
            allergenCategoryCode: 'SULFA',
            price: 2000,
        },
        // Giảm đau - kháng viêm
        {
            drugCode: 'IBU400',
            drugName: 'Ibuprofen 400mg',
            genericName: 'Ibuprofen',
            strength: '400mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'NSAID',
            allergenCategoryCode: 'NSAID',
            price: 1500,
        },
        {
            drugCode: 'DICLO50',
            drugName: 'Diclofenac 50mg',
            genericName: 'Diclofenac',
            strength: '50mg',
            dosageForm: 'viên bao tan trong ruột',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'NSAID',
            allergenCategoryCode: 'NSAID',
            price: 1800,
        },
        {
            drugCode: 'NAPR250',
            drugName: 'Naproxen 250mg',
            genericName: 'Naproxen',
            strength: '250mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'NSAID',
            allergenCategoryCode: 'NSAID',
            price: 2200,
        },
        {
            drugCode: 'ASP81',
            drugName: 'Aspirin 81mg',
            genericName: 'Acetylsalicylic acid',
            strength: '81mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Kháng kết tập tiểu cầu',
            allergenCategoryCode: 'ASPIRIN',
            price: 800,
        },
        {
            drugCode: 'PARA500',
            drugName: 'Paracetamol 500mg',
            genericName: 'Paracetamol',
            strength: '500mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Giảm đau - hạ sốt',
            allergenCategoryCode: null,
            price: 500,
        },
        // Tiêu hóa
        {
            drugCode: 'OMEP20',
            drugName: 'Omeprazole 20mg',
            genericName: 'Omeprazole',
            strength: '20mg',
            dosageForm: 'viên nang',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Ức chế bơm proton (PPI)',
            allergenCategoryCode: null,
            price: 2500,
        },
        // Dị ứng - hô hấp
        {
            drugCode: 'LORA10',
            drugName: 'Loratadine 10mg',
            genericName: 'Loratadine',
            strength: '10mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Kháng histamin H1',
            allergenCategoryCode: null,
            price: 1200,
        },
        {
            drugCode: 'CETI10',
            drugName: 'Cetirizine 10mg',
            genericName: 'Cetirizine',
            strength: '10mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Kháng histamin H1',
            allergenCategoryCode: null,
            price: 1300,
        },
        {
            drugCode: 'SALB100',
            drugName: 'Salbutamol 100mcg',
            genericName: 'Salbutamol',
            strength: '100mcg/liều xịt',
            dosageForm: 'bình xịt định liều',
            route: 'inhalation',
            unit: 'bình',
            therapeuticClass: 'Giãn phế quản',
            allergenCategoryCode: null,
            price: 65000,
        },
        // Chuyển hóa - tim mạch
        {
            drugCode: 'METF500',
            drugName: 'Metformin 500mg',
            genericName: 'Metformin',
            strength: '500mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Đái tháo đường',
            allergenCategoryCode: null,
            price: 1000,
        },
        {
            drugCode: 'AMLO5',
            drugName: 'Amlodipine 5mg',
            genericName: 'Amlodipine',
            strength: '5mg',
            dosageForm: 'viên nén',
            route: 'oral',
            unit: 'viên',
            therapeuticClass: 'Tim mạch - hạ áp',
            allergenCategoryCode: null,
            price: 1500,
        },
    ];

    for (const d of drugs) {
        const allergenCategoryId = d.allergenCategoryCode ? categoryMap.get(d.allergenCategoryCode) : null;

        await prisma.drugCatalog.upsert({
            where: { drugCode: d.drugCode },
            update: {
                drugName: d.drugName,
                genericName: d.genericName,
                strength: d.strength,
                dosageForm: d.dosageForm,
                route: d.route,
                unit: d.unit,
                therapeuticClass: d.therapeuticClass,
                allergenCategoryId,
                price: d.price,
            },
            create: {
                drugCode: d.drugCode,
                drugName: d.drugName,
                genericName: d.genericName,
                strength: d.strength,
                dosageForm: d.dosageForm,
                route: d.route,
                unit: d.unit,
                therapeuticClass: d.therapeuticClass,
                allergenCategoryId,
                price: d.price,
                isActive: true,
            },
        });
    }

    const count = await prisma.drugCatalog.count();
    console.log(`Seeded drug catalog, total in DB: ${count}`);
}
