import { PrismaService } from 'prisma/prisma.service';

/**
 * Tương tác thuốc - nguồn: Dược thư Quốc gia Việt Nam, tờ hướng dẫn sử dụng thuốc
 * và DrugBank Drug Interaction Checker (go.drugbank.com).
 * severity: mild | moderate | severe
 */
export async function seedDrugInteractions(prisma: PrismaService): Promise<void> {
    const drugs = await prisma.drugCatalog.findMany();
    const drugMap = new Map(drugs.map((d) => [d.drugCode, d.drugId]));

    const interactions = [
        {
            drugCodeA: "ASP81",
            drugCodeB: "IBU400",
            severity: "severe",
            description: "Dùng đồng thời Ibuprofen với Aspirin liều thấp có thể làm giảm tác dụng kháng kết tập tiểu cầu của Aspirin và tăng nguy cơ xuất huyết tiêu hóa.",
        },
        {
            drugCodeA: "IBU400",
            drugCodeB: "DICLO50",
            severity: "moderate",
            description: "Phối hợp 2 NSAID cùng lúc không tăng hiệu quả giảm đau mà tăng nguy cơ loét dạ dày - tá tràng và độc tính trên thận.",
        },
        {
            drugCodeA: "ASP81",
            drugCodeB: "DICLO50",
            severity: "moderate",
            description: "Diclofenac dùng cùng Aspirin liều thấp có thể làm giảm tác dụng bảo vệ tim mạch của Aspirin và tăng nguy cơ tác dụng phụ trên đường tiêu hóa.",
        },
        {
            drugCodeA: "METF500",
            drugCodeB: "IBU400",
            severity: "moderate",
            description: "NSAID có thể làm giảm chức năng thận, dẫn tới tích lũy Metformin và tăng nguy cơ toan lactic.",
        },
        {
            drugCodeA: "OMEP20",
            drugCodeB: "METF500",
            severity: "mild",
            description: "Dùng PPI kéo dài cùng Metformin có thể ảnh hưởng hấp thu vitamin B12, cần theo dõi khi điều trị dài ngày.",
        },
        {
            drugCodeA: "WARFARIN",
            drugCodeB: "ASP81",
            severity: "severe",
            description: "Cộng hợp tác dụng chống đông và ức chế tiểu cầu. Tăng nguy cơ xuất huyết nặng - tránh phối hợp trừ khi có chỉ định đặc biệt.",
        },
        {
            drugCodeA: "WARFARIN",
            drugCodeB: "IBU400",
            severity: "severe",
            description: "NSAID làm tăng tác dụng chống đông và gây loét/xuất huyết tiêu hóa. Tránh phối hợp; theo dõi INR sát nếu bắt buộc dùng.",
        },
        {
            drugCodeA: "WARFARIN",
            drugCodeB: "AUGM625",
            severity: "moderate",
            description: "Kháng sinh phổ rộng làm giảm hệ vi khuẩn tổng hợp Vitamin K. Theo dõi INR khi bắt đầu/ngừng kháng sinh.",
        },
        {
            drugCodeA: "WARFARIN",
            drugCodeB: "METRONIDAZOLE",
            severity: "severe",
            description: "Ức chế men CYP2C9 chuyển hóa Warfarin. Tăng mạnh tác dụng chống đông - giảm liều Warfarin và theo dõi INR.",
        },
        {
            drugCodeA: "WARFARIN",
            drugCodeB: "CIPROFLOXACIN",
            severity: "moderate",
            description: "Ức chế chuyển hóa Warfarin qua CYP. Theo dõi INR, có thể cần giảm liều Warfarin.",
        },
        {
            drugCodeA: "CLOPIDOGREL",
            drugCodeB: "OMEP20",
            severity: "moderate",
            description: "Omeprazole ức chế CYP2C19 làm giảm hoạt hóa Clopidogrel. Giảm hiệu quả chống kết tập tiểu cầu - cân nhắc dùng Pantoprazole thay thế.",
        },
        {
            drugCodeA: "CLOPIDOGREL",
            drugCodeB: "ASP81",
            severity: "moderate",
            description: "Cộng hợp ức chế tiểu cầu (phối hợp có chủ đích trong hội chứng vành cấp). Theo dõi nguy cơ xuất huyết, chỉ phối hợp khi có chỉ định.",
        },
        {
            drugCodeA: "DIGOXIN",
            drugCodeB: "FUROSEMIDE",
            severity: "moderate",
            description: "Lợi tiểu gây hạ Kali máu làm tăng độc tính Digoxin. Theo dõi điện giải đồ (Kali) và nồng độ Digoxin.",
        },
        {
            drugCodeA: "DIGOXIN",
            drugCodeB: "AMIODARONHYDRO",
            severity: "severe",
            description: "Amiodarone làm tăng nồng độ Digoxin trong máu. Giảm liều Digoxin khoảng 50% khi phối hợp.",
        },
        {
            drugCodeA: "ENALAPRIL",
            drugCodeB: "SPIRONOLACTONE",
            severity: "severe",
            description: "Cộng hợp giữ Kali gây tăng Kali máu. Theo dõi Kali máu và chức năng thận định kỳ.",
        },
        {
            drugCodeA: "ENALAPRIL",
            drugCodeB: "LOSARTAN",
            severity: "severe",
            description: "Cộng hợp ức chế hệ Renin-Angiotensin gây tụt huyết áp và suy thận. Không khuyến cáo phối hợp 2 nhóm cùng cơ chế.",
        },
        {
            drugCodeA: "ENALAPRIL",
            drugCodeB: "IBU400",
            severity: "moderate",
            description: "NSAID làm giảm hiệu quả hạ áp và tăng nguy cơ suy thận. Theo dõi huyết áp và chức năng thận; hạn chế dùng NSAID kéo dài.",
        },
        {
            drugCodeA: "AMLO5",
            drugCodeB: "SIMVASTATIN",
            severity: "moderate",
            description: "Amlodipine ức chế CYP3A4 làm tăng nồng độ Statin. Giới hạn liều Simvastatin khi phối hợp (thường không quá 20mg/ngày).",
        },
        {
            drugCodeA: "ATORVASTATIN",
            drugCodeB: "CLARITHROMYCIN",
            severity: "severe",
            description: "Clarithromycin ức chế mạnh CYP3A4 chuyển hóa Statin. Tăng nguy cơ tiêu cơ vân - tạm ngừng Statin trong đợt dùng kháng sinh.",
        },
        {
            drugCodeA: "METF500",
            drugCodeB: "FUROSEMIDE",
            severity: "mild",
            description: "Lợi tiểu có thể ảnh hưởng chức năng thận, gián tiếp ảnh hưởng thải trừ Metformin. Theo dõi chức năng thận định kỳ.",
        },
        {
            drugCodeA: "GLICLAZIDE",
            drugCodeB: "BACTRIM480",
            severity: "moderate",
            description: "Sulfamethoxazole ức chế chuyển hóa Sulfonylurea. Tăng nguy cơ hạ đường huyết - theo dõi đường huyết sát.",
        },
        {
            drugCodeA: "INSULINREGULAR",
            drugCodeB: "BISOPROLOL",
            severity: "moderate",
            description: "Chẹn beta che lấp triệu chứng hạ đường huyết (run, tim nhanh). Cảnh báo bệnh nhân về nguy cơ hạ đường huyết không triệu chứng.",
        },
        {
            drugCodeA: "LEVOTHYROXINE",
            drugCodeB: "CALCIUMCARBONA",
            severity: "moderate",
            description: "Calci làm giảm hấp thu Levothyroxine qua đường uống. Uống cách nhau tối thiểu 4 giờ.",
        },
        {
            drugCodeA: "LEVOTHYROXINE",
            drugCodeB: "OMEP20",
            severity: "mild",
            description: "PPI làm giảm hấp thu Levothyroxine do thay đổi pH dạ dày. Theo dõi TSH, có thể cần điều chỉnh liều.",
        },
        {
            drugCodeA: "THEOPHYLLINE",
            drugCodeB: "CIPROFLOXACIN",
            severity: "severe",
            description: "Ciprofloxacin ức chế CYP1A2 làm tăng nồng độ Theophylline. Nguy cơ ngộ độc Theophylline (co giật, loạn nhịp) - tránh phối hợp.",
        },
        {
            drugCodeA: "THEOPHYLLINE",
            drugCodeB: "CLARITHROMYCIN",
            severity: "moderate",
            description: "Ức chế CYP3A4/1A2 làm tăng nồng độ Theophylline. Theo dõi nồng độ thuốc và triệu chứng ngộ độc.",
        },
        {
            drugCodeA: "SERTRALINE",
            drugCodeB: "TRAMADOL",
            severity: "severe",
            description: "Cộng hợp Serotonin - hội chứng Serotonin. Tránh phối hợp hoặc theo dõi sát dấu hiệu (kích động, sốt, run).",
        },
        {
            drugCodeA: "FLUOXETINE",
            drugCodeB: "AMITRIPTYLINE",
            severity: "moderate",
            description: "Ức chế CYP2D6 làm tăng nồng độ thuốc ba vòng. Theo dõi độc tính tim mạch và thần kinh.",
        },
        {
            drugCodeA: "SERTRALINE",
            drugCodeB: "ASP81",
            severity: "moderate",
            description: "SSRI làm giảm hấp thu Serotonin của tiểu cầu, cộng hợp tăng nguy cơ xuất huyết. Theo dõi dấu hiệu xuất huyết tiêu hóa.",
        },
        {
            drugCodeA: "DIAZEPAMUONG",
            drugCodeB: "TRAMADOL",
            severity: "moderate",
            description: "Cộng hợp ức chế thần kinh trung ương. Tăng nguy cơ an thần quá mức, ức chế hô hấp - thận trọng khi phối hợp.",
        },
        {
            drugCodeA: "PHENYTOIN",
            drugCodeB: "WARFARIN",
            severity: "moderate",
            description: "Tương tác hai chiều qua CYP2C9, khó dự đoán. Theo dõi sát INR và nồng độ Phenytoin.",
        },
        {
            drugCodeA: "VALPROICACID",
            drugCodeB: "PHENYTOIN",
            severity: "moderate",
            description: "Cạnh tranh gắn kết protein huyết tương, thay đổi nồng độ tự do. Theo dõi nồng độ thuốc trong máu.",
        },
        {
            drugCodeA: "CINNARIZINE",
            drugCodeB: "BETAHISTINE",
            severity: "mild",
            description: "Có thể đối kháng một phần hiệu quả điều trị chóng mặt. Không phải chống chỉ định tuyệt đối, theo dõi đáp ứng lâm sàng.",
        },
        {
            drugCodeA: "PREDNISOLONE",
            drugCodeB: "IBU400",
            severity: "severe",
            description: "Cộng hợp gây loét và xuất huyết tiêu hóa. Cân nhắc dùng kèm PPI bảo vệ dạ dày nếu bắt buộc phối hợp.",
        },
        {
            drugCodeA: "PREDNISOLONE",
            drugCodeB: "METF500",
            severity: "mild",
            description: "Corticosteroid làm tăng đường huyết, đối kháng hiệu quả hạ đường huyết. Theo dõi và điều chỉnh liều thuốc hạ đường huyết.",
        },
        {
            drugCodeA: "LORA10",
            drugCodeB: "ERYTHROMYCIN",
            severity: "mild",
            description: "Ức chế CYP3A4 làm tăng nồng độ kháng Histamin. Hiếm khi có ý nghĩa lâm sàng với thế hệ 2, vẫn nên thận trọng.",
        },
        {
            drugCodeA: "DOMPERIDONE",
            drugCodeB: "FLUCONAZOLE",
            severity: "moderate",
            description: "Ức chế CYP3A4 làm tăng nồng độ Domperidone, kéo dài khoảng QT. Tránh phối hợp hoặc theo dõi điện tâm đồ.",
        },
        {
            drugCodeA: "CIPROFLOXACIN",
            drugCodeB: "CALCIUMCARBONA",
            severity: "moderate",
            description: "Calci tạo phức chelat làm giảm hấp thu Quinolon. Uống Quinolon cách xa Calci/sắt/kẽm tối thiểu 2 giờ.",
        },
        {
            drugCodeA: "DOXYCYCLINE",
            drugCodeB: "CALCIUMCARBONA",
            severity: "moderate",
            description: "Calci tạo phức chelat làm giảm hấp thu Tetracyclin. Uống cách nhau tối thiểu 2-3 giờ.",
        },
        {
            drugCodeA: "SATACIDFOLIC",
            drugCodeB: "CIPROFLOXACIN",
            severity: "moderate",
            description: "Sắt tạo phức chelat làm giảm hấp thu Quinolon. Uống cách nhau tối thiểu 2 giờ.",
        },
        {
            drugCodeA: "ALLOPURINOL",
            drugCodeB: "AZATHIOPRIN",
            severity: "severe",
            description: "Allopurinol ức chế enzym xanthin oxidase chuyển hóa Azathioprine. Nguy cơ suy tủy nặng - giảm liều Azathioprine còn 25% hoặc tránh phối hợp.",
        },
        {
            drugCodeA: "COLCHICINE",
            drugCodeB: "CLARITHROMYCIN",
            severity: "severe",
            description: "Ức chế CYP3A4/P-glycoprotein làm tăng độc tính Colchicine. Nguy cơ ngộ độc nặng - tránh phối hợp, đặc biệt ở người suy thận/gan.",
        },
        {
            drugCodeA: "METRONIDAZOLE",
            drugCodeB: "ASP81",
            severity: "mild",
            description: "Phản ứng giống Disulfiram khi dùng cùng rượu, không tương tác trực tiếp với Aspirin. Dặn bệnh nhân tránh rượu bia trong và sau điều trị Metronidazole.",
        },
        {
            drugCodeA: "MONTELUKAST",
            drugCodeB: "PHENYTOIN",
            severity: "mild",
            description: "Phenytoin cảm ứng enzym có thể làm giảm nồng độ Montelukast. Theo dõi hiệu quả kiểm soát hen nếu phối hợp kéo dài.",
        },
        {
            drugCodeA: "RANITIDINE",
            drugCodeB: "FLUCONAZOLE",
            severity: "moderate",
            description: "Thuốc kháng H2/PPI làm giảm hấp thu thuốc kháng nấm nhóm azol cần môi trường acid. Uống thuốc kháng nấm cách xa thời điểm dùng thuốc giảm tiết acid.",
        },
        {
            drugCodeA: "MELOXICAM",
            drugCodeB: "LOSARTAN",
            severity: "moderate",
            description: "NSAID làm giảm hiệu quả hạ áp của ARB và tăng nguy cơ suy thận. Theo dõi huyết áp, chức năng thận nếu phối hợp lâu dài.",
        },
        {
            drugCodeA: "PIROXICAM",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "NSAID mạnh làm tăng nguy cơ xuất huyết tiêu hóa khi phối hợp chống đông. Tránh phối hợp.",
        },
        {
            drugCodeA: "TRAMADOL",
            drugCodeB: "FLUOXETINE",
            severity: "severe",
            description: "Cộng hợp Serotonin, nguy cơ hội chứng Serotonin. Tránh phối hợp hoặc giám sát chặt chẽ.",
        },
        {
            drugCodeA: "SPIRONOLACTONE",
            drugCodeB: "LOSARTAN",
            severity: "severe",
            description: "Cộng hợp giữ Kali gây tăng Kali máu. Theo dõi điện giải đồ định kỳ.",
        },
        {
            drugCodeA: "VERAPAMILHYDRO",
            drugCodeB: "ATENOLOL",
            severity: "severe",
            description: "Cộng hợp ức chế nút nhĩ thất, nguy cơ block tim và suy tim nặng. Tránh phối hợp đường tĩnh mạch; nếu uống cần theo dõi ECG sát.",
        },
        {
            drugCodeA: "DILTIAZEM",
            drugCodeB: "SIMVASTATIN",
            severity: "severe",
            description: "Ức chế CYP3A4 làm tăng nồng độ Statin, tăng nguy cơ tiêu cơ vân. Giới hạn liều Simvastatin (thường không quá 10mg/ngày) khi phối hợp.",
        },
        {
            drugCodeA: "AMIODARONHYDRO",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Ức chế CYP2C9 làm tăng tác dụng chống đông. Giảm liều Warfarin 30-50% và theo dõi INR sát.",
        },
        {
            drugCodeA: "AMIODARONHYDRO",
            drugCodeB: "SIMVASTATIN",
            severity: "severe",
            description: "Ức chế CYP3A4 làm tăng nồng độ Statin. Giới hạn liều Statin khi phối hợp, theo dõi CK máu.",
        },
        {
            drugCodeA: "NIFEDIPIN",
            drugCodeB: "ATENOLOL",
            severity: "moderate",
            description: "Cộng hợp hạ huyết áp và giảm co bóp cơ tim. Theo dõi huyết áp và nhịp tim khi khởi đầu phối hợp.",
        },
        {
            drugCodeA: "CAPTOPRIL",
            drugCodeB: "SPIRONOLACTONE",
            severity: "severe",
            description: "Cộng hợp giữ Kali gây tăng Kali máu. Theo dõi điện giải đồ định kỳ, đặc biệt ở người suy thận.",
        },
        {
            drugCodeA: "CAPTOPRIL",
            drugCodeB: "IBU400",
            severity: "moderate",
            description: "NSAID làm giảm hiệu quả hạ áp và tăng nguy cơ suy thận cấp. Theo dõi huyết áp và chức năng thận, hạn chế dùng NSAID kéo dài.",
        },
        {
            drugCodeA: "METHYLDOPA",
            drugCodeB: "PROPRANOLOLHYD",
            severity: "moderate",
            description: "Cộng hợp hạ huyết áp quá mức, có báo cáo tăng huyết áp nghịch thường khi phối hợp một số chẹn beta. Theo dõi huyết áp sát khi khởi đầu hoặc ngừng phối hợp.",
        },
        {
            drugCodeA: "DOBUTAMIN",
            drugCodeB: "PROPRANOLOLHYD",
            severity: "moderate",
            description: "Chẹn beta đối kháng tác dụng cường beta của Dobutamin. Tránh phối hợp trong cấp cứu suy tim cấp; theo dõi đáp ứng huyết động.",
        },
        {
            drugCodeA: "DOPAMINHYDROCL",
            drugCodeB: "PHENYTOIN",
            severity: "moderate",
            description: "Phối hợp qua đường tĩnh mạch có thể gây tụt huyết áp và loạn nhịp. Tránh dùng đồng thời qua đường tĩnh mạch, theo dõi huyết động.",
        },
        {
            drugCodeA: "STREPTOKINASE",
            drugCodeB: "ASP81",
            severity: "severe",
            description: "Cộng hợp tiêu sợi huyết và ức chế tiểu cầu làm tăng nguy cơ xuất huyết nặng. Cân nhắc lợi ích/nguy cơ theo phác đồ hội chứng vành cấp, theo dõi sát dấu hiệu xuất huyết.",
        },
        {
            drugCodeA: "STREPTOKINASE",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Cộng hợp tiêu sợi huyết và chống đông làm tăng mạnh nguy cơ xuất huyết. Chống chỉ định phối hợp trong hầu hết trường hợp; chỉ dùng dưới giám sát chuyên khoa.",
        },
        {
            drugCodeA: "FENOFIBRAT",
            drugCodeB: "WARFARIN",
            severity: "moderate",
            description: "Fenofibrat làm tăng tác dụng chống đông qua cạnh tranh gắn kết protein huyết tương. Theo dõi INR sát khi bắt đầu hoặc ngừng Fenofibrat.",
        },
        {
            drugCodeA: "FENOFIBRAT",
            drugCodeB: "SIMVASTATIN",
            severity: "severe",
            description: "Cộng hợp 2 nhóm hạ lipid máu làm tăng nguy cơ tiêu cơ vân. Cân nhắc kỹ lợi ích/nguy cơ, theo dõi CK và chức năng thận.",
        },
        {
            drugCodeA: "PROPRANOLOLHYD",
            drugCodeB: "INSULINREGULAR",
            severity: "moderate",
            description: "Chẹn beta không chọn lọc che lấp triệu chứng hạ đường huyết. Cảnh báo bệnh nhân đái tháo đường về nguy cơ hạ đường huyết không triệu chứng.",
        },
        {
            drugCodeA: "POVIDONIOD",
            drugCodeB: "LITHICARBONAT",
            severity: "mild",
            description: "Hấp thu iod qua da/niêm mạc diện rộng có thể ảnh hưởng chức năng tuyến giáp khi dùng kéo dài. Tránh sát khuẩn diện rộng kéo dài ở bệnh nhân có bệnh lý tuyến giáp.",
        },
        {
            drugCodeA: "HYDRALAZIN",
            drugCodeB: "IBU400",
            severity: "moderate",
            description: "NSAID làm giảm hiệu quả hạ áp của Hydralazin qua ức chế tổng hợp Prostaglandin. Theo dõi huyết áp nếu phối hợp kéo dài.",
        },
        {
            drugCodeA: "THEOPHYLLINE",
            drugCodeB: "BECLOMETASONDI",
            severity: "mild",
            description: "Không có tương tác dược động học đáng kể nhưng phối hợp hợp lý trong kiểm soát hen. An toàn khi phối hợp theo phác đồ điều trị hen/COPD.",
        },
        {
            drugCodeA: "SALB100",
            drugCodeB: "PROPRANOLOLHYD",
            severity: "severe",
            description: "Chẹn beta không chọn lọc đối kháng trực tiếp tác dụng giãn phế quản của Salbutamol. Tránh dùng chẹn beta không chọn lọc ở bệnh nhân hen/COPD đang dùng Salbutamol.",
        },
        {
            drugCodeA: "IPRATROPIUMBRO",
            drugCodeB: "SALB100",
            severity: "mild",
            description: "Cộng hợp tác dụng giãn phế quản qua 2 cơ chế khác nhau (phối hợp có chủ đích). Phối hợp thường quy và an toàn trong điều trị COPD/hen nặng.",
        },
        {
            drugCodeA: "TERBUTALIN",
            drugCodeB: "DIGOXIN",
            severity: "moderate",
            description: "Thuốc cường beta-2 có thể gây hạ Kali máu làm tăng độc tính Digoxin. Theo dõi điện giải đồ và triệu chứng ngộ độc Digoxin khi phối hợp.",
        },
        {
            drugCodeA: "IOHEXOL",
            drugCodeB: "METF500",
            severity: "severe",
            description: "Thuốc cản quang chứa iod có thể gây suy thận cấp, làm tích lũy Metformin dẫn đến nhiễm toan lactic. Ngừng Metformin trước và 48h sau khi dùng thuốc cản quang, đánh giá lại chức năng thận trước khi dùng lại.",
        },
        {
            drugCodeA: "RIFAMPICIN",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Cảm ứng mạnh CYP2C9/CYP3A4 làm tăng chuyển hóa Warfarin. Giảm mạnh hiệu lực chống đông - theo dõi INR sát, thường phải tăng liều Warfarin.",
        },
        {
            drugCodeA: "RIFAMPICIN",
            drugCodeB: "ETHINYLESTRADI",
            severity: "severe",
            description: "Cảm ứng CYP3A4 làm giảm nồng độ hormon tránh thai. Nguy cơ thất bại tránh thai - dùng biện pháp tránh thai bổ sung không nội tiết.",
        },
        {
            drugCodeA: "RIFAMPICIN",
            drugCodeB: "ISONIAZID",
            severity: "moderate",
            description: "Cộng hợp độc tính trên gan. Phối hợp bắt buộc trong phác đồ lao - theo dõi men gan định kỳ.",
        },
        {
            drugCodeA: "RIFAMPICIN",
            drugCodeB: "NEVIRAPIN",
            severity: "severe",
            description: "Cảm ứng CYP3A4 làm giảm nồng độ Nevirapin. Tránh phối hợp; ưu tiên Efavirenz trong phác đồ ARV có Rifampicin.",
        },
        {
            drugCodeA: "RIFAMPICIN",
            drugCodeB: "LOPINAVIRRITON",
            severity: "severe",
            description: "Cảm ứng CYP3A4 làm giảm mạnh nồng độ thuốc ức chế protease. Chống chỉ định phối hợp - thay bằng Rifabutin.",
        },
        {
            drugCodeA: "RIFAMPICIN",
            drugCodeB: "ATORVASTATIN",
            severity: "moderate",
            description: "Cảm ứng CYP3A4 và ức chế OATP1B1 làm thay đổi nồng độ statin. Theo dõi hiệu quả hạ lipid; cân nhắc điều chỉnh liều.",
        },
        {
            drugCodeA: "RIFAMPICIN",
            drugCodeB: "DIGOXIN",
            severity: "moderate",
            description: "Cảm ứng P-glycoprotein làm giảm hấp thu Digoxin. Theo dõi nồng độ Digoxin huyết thanh.",
        },
        {
            drugCodeA: "RIFAMPICIN",
            drugCodeB: "CICLOSPORIN",
            severity: "severe",
            description: "Cảm ứng CYP3A4 làm giảm mạnh nồng độ Ciclosporin. Nguy cơ thải ghép - theo dõi nồng độ và tăng liều Ciclosporin.",
        },
        {
            drugCodeA: "ISONIAZID",
            drugCodeB: "PHENYTOIN",
            severity: "severe",
            description: "Ức chế CYP2C19 làm giảm chuyển hóa Phenytoin. Tăng nguy cơ ngộ độc Phenytoin - theo dõi nồng độ, giảm liều.",
        },
        {
            drugCodeA: "ISONIAZID",
            drugCodeB: "CARBAMAZEPIN",
            severity: "severe",
            description: "Ức chế chuyển hóa Carbamazepin và tăng độc tính gan. Theo dõi nồng độ Carbamazepin và men gan.",
        },
        {
            drugCodeA: "ISONIAZID",
            drugCodeB: "PYRIDOXINVITAM",
            severity: "mild",
            description: "Isoniazid gây thiếu hụt Vitamin B6 dẫn tới bệnh thần kinh ngoại biên. Phối hợp có lợi - bổ sung B6 25-50mg/ngày khi dùng Isoniazid.",
        },
        {
            drugCodeA: "ISONIAZID",
            drugCodeB: "PARA500",
            severity: "moderate",
            description: "Cảm ứng CYP2E1 làm tăng chất chuyển hóa độc gan của Paracetamol. Hạn chế liều Paracetamol; theo dõi men gan.",
        },
        {
            drugCodeA: "LEVOFLOXACIN",
            drugCodeB: "MAGNESIHYDROXY",
            severity: "moderate",
            description: "Tạo phức chelat với cation hóa trị 2-3 làm giảm hấp thu Quinolon. Uống cách nhau ít nhất 2 giờ trước hoặc 6 giờ sau antacid.",
        },
        {
            drugCodeA: "CIPROFLOXACIN",
            drugCodeB: "KEMSULFAT",
            severity: "moderate",
            description: "Tạo phức chelat làm giảm sinh khả dụng Quinolon. Uống cách xa nhau ít nhất 2 giờ.",
        },
        {
            drugCodeA: "LEVOFLOXACIN",
            drugCodeB: "AMIODARONHYDRO",
            severity: "severe",
            description: "Cộng hợp kéo dài khoảng QT. Nguy cơ xoắn đỉnh - tránh phối hợp, theo dõi ECG nếu bắt buộc.",
        },
        {
            drugCodeA: "LEVOFLOXACIN",
            drugCodeB: "GLIBENCLAMID",
            severity: "moderate",
            description: "Quinolon làm rối loạn điều hòa đường huyết. Theo dõi đường huyết chặt, cảnh báo hạ đường huyết.",
        },
        {
            drugCodeA: "CLARITHROMYCIN",
            drugCodeB: "SIMVASTATIN",
            severity: "severe",
            description: "Ức chế mạnh CYP3A4 làm tăng nồng độ statin. Nguy cơ tiêu cơ vân - chống chỉ định phối hợp, ngừng statin trong đợt kháng sinh.",
        },
        {
            drugCodeA: "CLARITHROMYCIN",
            drugCodeB: "DIGOXIN",
            severity: "severe",
            description: "Ức chế P-glycoprotein và giảm vi khuẩn ruột chuyển hóa Digoxin. Tăng nồng độ Digoxin - theo dõi nồng độ và dấu hiệu ngộ độc.",
        },
        {
            drugCodeA: "CLARITHROMYCIN",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Ức chế CYP3A4 làm tăng tác dụng chống đông. Theo dõi INR chặt trong và sau đợt điều trị.",
        },
        {
            drugCodeA: "ERYTHROMYCIN",
            drugCodeB: "AMIODARONHYDRO",
            severity: "severe",
            description: "Cộng hợp kéo dài khoảng QT. Nguy cơ xoắn đỉnh - tránh phối hợp.",
        },
        {
            drugCodeA: "ERYTHROMYCIN",
            drugCodeB: "CARBAMAZEPIN",
            severity: "severe",
            description: "Ức chế CYP3A4 làm giảm chuyển hóa Carbamazepin. Tăng nguy cơ ngộ độc - theo dõi nồng độ, giảm liều.",
        },
        {
            drugCodeA: "GENTAMICIN",
            drugCodeB: "FUROSEMIDE",
            severity: "severe",
            description: "Cộng hợp độc tính trên tai và thận. Nguy cơ điếc không hồi phục và suy thận - tránh phối hợp, theo dõi creatinin.",
        },
        {
            drugCodeA: "GENTAMICIN",
            drugCodeB: "VANCOMYCIN",
            severity: "severe",
            description: "Cộng hợp độc tính trên thận. Theo dõi chức năng thận và nồng độ đáy Vancomycin.",
        },
        {
            drugCodeA: "GENTAMICIN",
            drugCodeB: "SUXAMETHONIUMC",
            severity: "severe",
            description: "Aminoglycosid tăng cường phong bế thần kinh cơ. Kéo dài liệt cơ và suy hô hấp - thận trọng trong gây mê.",
        },
        {
            drugCodeA: "AMIKACIN",
            drugCodeB: "FUROSEMIDE",
            severity: "severe",
            description: "Cộng hợp độc tính trên tai và thận. Tránh phối hợp; nếu bắt buộc phải theo dõi thính lực và chức năng thận.",
        },
        {
            drugCodeA: "VANCOMYCIN",
            drugCodeB: "CICLOSPORIN",
            severity: "severe",
            description: "Cộng hợp độc tính trên thận. Theo dõi creatinin và nồng độ Ciclosporin.",
        },
        {
            drugCodeA: "CLORAMPHENICOL",
            drugCodeB: "PHENYTOIN",
            severity: "severe",
            description: "Ức chế CYP2C9 làm giảm chuyển hóa Phenytoin. Tăng nguy cơ ngộ độc Phenytoin - theo dõi nồng độ.",
        },
        {
            drugCodeA: "CLORAMPHENICOL",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Ức chế chuyển hóa Warfarin. Tăng nguy cơ xuất huyết - theo dõi INR.",
        },
        {
            drugCodeA: "CLINDAMYCIN",
            drugCodeB: "VECURONIUMBROM",
            severity: "moderate",
            description: "Tăng cường phong bế thần kinh cơ. Kéo dài tác dụng giãn cơ - thận trọng khi gây mê.",
        },
        {
            drugCodeA: "NITROFURANTOIN",
            drugCodeB: "MAGNESIHYDROXY",
            severity: "mild",
            description: "Antacid chứa magnesi làm giảm hấp thu Nitrofurantoin. Uống cách xa nhau ít nhất 2 giờ.",
        },
        {
            drugCodeA: "BACTRIM480",
            drugCodeB: "METHOTREXAT",
            severity: "severe",
            description: "Cộng hợp ức chế chuyển hóa folat và đẩy Methotrexat khỏi protein. Nguy cơ suy tủy nặng - chống chỉ định phối hợp.",
        },
        {
            drugCodeA: "BACTRIM480",
            drugCodeB: "GLIBENCLAMID",
            severity: "moderate",
            description: "Ức chế CYP2C9 làm tăng tác dụng Sulfonylurea. Nguy cơ hạ đường huyết - theo dõi đường huyết.",
        },
        {
            drugCodeA: "BACTRIM480",
            drugCodeB: "SPIRONOLACTONE",
            severity: "severe",
            description: "Cộng hợp giữ kali. Nguy cơ tăng kali máu nặng - tránh phối hợp ở người cao tuổi/suy thận.",
        },
        {
            drugCodeA: "FLUCONAZOLE",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Ức chế CYP2C9 làm giảm chuyển hóa Warfarin. Tăng mạnh INR - giảm liều Warfarin và theo dõi sát.",
        },
        {
            drugCodeA: "FLUCONAZOLE",
            drugCodeB: "PHENYTOIN",
            severity: "severe",
            description: "Ức chế CYP2C9 làm tăng nồng độ Phenytoin. Theo dõi nồng độ Phenytoin, giảm liều.",
        },
        {
            drugCodeA: "FLUCONAZOLE",
            drugCodeB: "AMIODARONHYDRO",
            severity: "severe",
            description: "Cộng hợp kéo dài khoảng QT. Nguy cơ xoắn đỉnh - tránh phối hợp.",
        },
        {
            drugCodeA: "FLUCONAZOLE",
            drugCodeB: "GLIBENCLAMID",
            severity: "moderate",
            description: "Ức chế CYP2C9 làm tăng nồng độ Sulfonylurea. Theo dõi đường huyết, cảnh báo hạ đường huyết.",
        },
        {
            drugCodeA: "KETOCONAZOL",
            drugCodeB: "SIMVASTATIN",
            severity: "severe",
            description: "Ức chế mạnh CYP3A4. Nguy cơ tiêu cơ vân - tránh phối hợp.",
        },
        {
            drugCodeA: "AMPHOTERICINB",
            drugCodeB: "FUROSEMIDE",
            severity: "severe",
            description: "Cộng hợp mất kali và độc tính thận. Nguy cơ hạ kali máu nặng - theo dõi điện giải và chức năng thận.",
        },
        {
            drugCodeA: "AMPHOTERICINB",
            drugCodeB: "DIGOXIN",
            severity: "severe",
            description: "Hạ kali máu do Amphotericin làm tăng độc tính Digoxin. Theo dõi kali máu và nồng độ Digoxin.",
        },
        {
            drugCodeA: "RITONAVIR",
            drugCodeB: "SIMVASTATIN",
            severity: "severe",
            description: "Ức chế rất mạnh CYP3A4. Chống chỉ định phối hợp - nguy cơ tiêu cơ vân.",
        },
        {
            drugCodeA: "RITONAVIR",
            drugCodeB: "MIDAZOLAM",
            severity: "severe",
            description: "Ức chế CYP3A4 làm tăng mạnh nồng độ Midazolam. An thần kéo dài, ức chế hô hấp - chống chỉ định đường uống.",
        },
        {
            drugCodeA: "EFAVIRENZ",
            drugCodeB: "ETHINYLESTRADI",
            severity: "severe",
            description: "Cảm ứng CYP3A4 làm giảm nồng độ hormon. Nguy cơ thất bại tránh thai - dùng biện pháp bổ sung.",
        },
        {
            drugCodeA: "EFAVIRENZ",
            drugCodeB: "METHADON",
            severity: "severe",
            description: "Cảm ứng CYP3A4 làm giảm nồng độ Methadon. Gây hội chứng cai - cần tăng liều Methadon và theo dõi.",
        },
        {
            drugCodeA: "TENOFOVIRDISOP",
            drugCodeB: "GENTAMICIN",
            severity: "moderate",
            description: "Cộng hợp độc tính trên ống thận. Theo dõi creatinin và phosphat máu.",
        },
        {
            drugCodeA: "ZIDOVUDIN",
            drugCodeB: "RIBAVIRIN",
            severity: "severe",
            description: "Ribavirin đối kháng phosphoryl hóa Zidovudin và cộng hợp gây thiếu máu. Giảm hiệu lực kháng virus và nguy cơ thiếu máu nặng - tránh phối hợp.",
        },
        {
            drugCodeA: "ZIDOVUDIN",
            drugCodeB: "BACTRIM480",
            severity: "moderate",
            description: "Cộng hợp ức chế tủy xương. Theo dõi công thức máu, đặc biệt bạch cầu trung tính.",
        },
        {
            drugCodeA: "ACYCLOVIR",
            drugCodeB: "GENTAMICIN",
            severity: "moderate",
            description: "Cộng hợp độc tính trên thận. Bù đủ dịch, theo dõi chức năng thận.",
        },
        {
            drugCodeA: "AMIODARONHYDRO",
            drugCodeB: "BISOPROLOL",
            severity: "severe",
            description: "Cộng hợp ức chế nút xoang và nút nhĩ thất. Nguy cơ nhịp chậm nặng, block nhĩ thất - theo dõi ECG.",
        },
        {
            drugCodeA: "DIGOXIN",
            drugCodeB: "VERAPAMILHYDRO",
            severity: "severe",
            description: "Ức chế P-glycoprotein làm tăng nồng độ Digoxin. Giảm liều Digoxin, theo dõi nồng độ và nhịp tim.",
        },
        {
            drugCodeA: "DIGOXIN",
            drugCodeB: "SPIRONOLACTONE",
            severity: "moderate",
            description: "Spironolacton làm giảm thải trừ Digoxin qua thận. Theo dõi nồng độ Digoxin và kali máu.",
        },
        {
            drugCodeA: "VERAPAMILHYDRO",
            drugCodeB: "BISOPROLOL",
            severity: "severe",
            description: "Cộng hợp ức chế co bóp cơ tim và dẫn truyền nhĩ thất. Nguy cơ block tim, suy tim cấp - tránh phối hợp đường tĩnh mạch.",
        },
        {
            drugCodeA: "HEPARINNATRI",
            drugCodeB: "ASP81",
            severity: "severe",
            description: "Cộng hợp chống đông và ức chế kết tập tiểu cầu. Tăng nguy cơ xuất huyết - chỉ phối hợp khi có chỉ định rõ, theo dõi sát.",
        },
        {
            drugCodeA: "HEPARINNATRI",
            drugCodeB: "CLOPIDOGREL",
            severity: "severe",
            description: "Cộng hợp tác dụng chống huyết khối. Chỉ dùng theo phác đồ hội chứng vành cấp, theo dõi dấu hiệu chảy máu.",
        },
        {
            drugCodeA: "ACENOCOUMAROL",
            drugCodeB: "ASP81",
            severity: "severe",
            description: "Cộng hợp chống đông và ức chế tiểu cầu, đẩy khỏi protein huyết tương. Tăng mạnh nguy cơ xuất huyết - tránh phối hợp.",
        },
        {
            drugCodeA: "ACENOCOUMAROL",
            drugCodeB: "AMIODARONHYDRO",
            severity: "severe",
            description: "Ức chế chuyển hóa thuốc kháng Vitamin K. Giảm liều Acenocoumarol và theo dõi INR.",
        },
        {
            drugCodeA: "ACENOCOUMAROL",
            drugCodeB: "VITAMINK1",
            severity: "severe",
            description: "Đối kháng dược lực học trực tiếp. Vitamin K1 là thuốc giải độc - chỉ dùng khi quá liều/xuất huyết.",
        },
        {
            drugCodeA: "WARFARIN",
            drugCodeB: "VITAMINK1",
            severity: "severe",
            description: "Đối kháng trực tiếp tác dụng chống đông. Dùng làm thuốc giải khi INR quá cao; tránh thay đổi đột ngột lượng Vitamin K trong chế độ ăn.",
        },
        {
            drugCodeA: "HEPARINNATRI",
            drugCodeB: "PROTAMINSULFAT",
            severity: "severe",
            description: "Protamin trung hòa trực tiếp Heparin. Thuốc giải độc chuyên biệt - dùng theo liều tính toán, nguy cơ hạ huyết áp.",
        },
        {
            drugCodeA: "ENALAPRIL",
            drugCodeB: "KALICLORID",
            severity: "severe",
            description: "Cộng hợp làm tăng kali máu. Tránh bổ sung kali trừ khi có bằng chứng hạ kali; theo dõi điện giải.",
        },
        {
            drugCodeA: "HYDROCLOROTHIA",
            drugCodeB: "DIGOXIN",
            severity: "severe",
            description: "Hạ kali máu làm tăng độc tính Digoxin. Bù kali, theo dõi điện giải.",
        },
        {
            drugCodeA: "HYDROCLOROTHIA",
            drugCodeB: "LITHICARBONAT",
            severity: "severe",
            description: "Giảm thải trừ Lithi qua thận. Nguy cơ ngộ độc Lithi - theo dõi nồng độ Lithi, giảm liều.",
        },
        {
            drugCodeA: "HYDROCLOROTHIA",
            drugCodeB: "ALLOPURINOL",
            severity: "moderate",
            description: "Thiazid làm tăng acid uric, đối kháng tác dụng của Allopurinol. Theo dõi acid uric máu; cân nhắc thuốc hạ áp khác ở bệnh nhân gout.",
        },
        {
            drugCodeA: "NIFEDIPIN",
            drugCodeB: "MAGNESISULFAT",
            severity: "severe",
            description: "Cộng hợp ức chế co bóp cơ và giãn mạch. Nguy cơ tụt huyết áp, block thần kinh cơ - thận trọng trong sản khoa.",
        },
        {
            drugCodeA: "LITHICARBONAT",
            drugCodeB: "IBU400",
            severity: "severe",
            description: "NSAID giảm thải trừ Lithi qua thận. Nguy cơ ngộ độc Lithi - tránh phối hợp, dùng Paracetamol thay thế.",
        },
        {
            drugCodeA: "LITHICARBONAT",
            drugCodeB: "ENALAPRIL",
            severity: "severe",
            description: "ACEI làm giảm thải trừ Lithi. Theo dõi nồng độ Lithi, giảm liều khi cần.",
        },
        {
            drugCodeA: "LITHICARBONAT",
            drugCodeB: "HALOPERIDOL",
            severity: "severe",
            description: "Cộng hợp độc tính trên thần kinh. Nguy cơ hội chứng ngoại tháp nặng, lú lẫn - theo dõi chặt.",
        },
        {
            drugCodeA: "HALOPERIDOL",
            drugCodeB: "AMIODARONHYDRO",
            severity: "severe",
            description: "Cộng hợp kéo dài khoảng QT. Nguy cơ xoắn đỉnh - theo dõi ECG, tránh phối hợp.",
        },
        {
            drugCodeA: "CLORPROMAZIN",
            drugCodeB: "TRAMADOL",
            severity: "severe",
            description: "Cộng hợp hạ ngưỡng co giật. Nguy cơ co giật - tránh phối hợp hoặc giảm liều.",
        },
        {
            drugCodeA: "CLORPROMAZIN",
            drugCodeB: "MORPHINHYDROCL",
            severity: "moderate",
            description: "Cộng hợp ức chế thần kinh trung ương và hạ huyết áp. Giảm liều, theo dõi hô hấp và huyết áp.",
        },
        {
            drugCodeA: "RISPERIDON",
            drugCodeB: "FLUOXETINE",
            severity: "moderate",
            description: "Ức chế CYP2D6 làm tăng nồng độ Risperidon. Nguy cơ ngoại tháp - giảm liều Risperidon.",
        },
        {
            drugCodeA: "CARBAMAZEPIN",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Cảm ứng CYP làm tăng chuyển hóa Warfarin. Giảm hiệu lực chống đông - theo dõi INR.",
        },
        {
            drugCodeA: "CARBAMAZEPIN",
            drugCodeB: "ETHINYLESTRADI",
            severity: "severe",
            description: "Cảm ứng enzym làm giảm nồng độ hormon. Nguy cơ thất bại tránh thai - dùng biện pháp bổ sung.",
        },
        {
            drugCodeA: "CARBAMAZEPIN",
            drugCodeB: "VALPROICACID",
            severity: "severe",
            description: "Tương tác hai chiều làm thay đổi nồng độ cả hai thuốc. Theo dõi nồng độ cả hai thuốc và dấu hiệu ngộ độc.",
        },
        {
            drugCodeA: "PHENOBARBITAL",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Cảm ứng enzym gan làm tăng chuyển hóa Warfarin. Giảm hiệu lực chống đông - theo dõi INR khi bắt đầu/ngừng.",
        },
        {
            drugCodeA: "PHENOBARBITAL",
            drugCodeB: "DIAZEPAMUONG",
            severity: "severe",
            description: "Cộng hợp ức chế thần kinh trung ương. Nguy cơ ức chế hô hấp, an thần quá mức - giảm liều.",
        },
        {
            drugCodeA: "PHENYTOIN",
            drugCodeB: "OMEP20",
            severity: "moderate",
            description: "Ức chế CYP2C19 làm tăng nồng độ Phenytoin. Theo dõi nồng độ Phenytoin.",
        },
        {
            drugCodeA: "MIDAZOLAM",
            drugCodeB: "MORPHINHYDROCL",
            severity: "severe",
            description: "Cộng hợp ức chế hô hấp và thần kinh trung ương. Nguy cơ ngừng thở - giảm liều, theo dõi SpO2 liên tục.",
        },
        {
            drugCodeA: "MIDAZOLAM",
            drugCodeB: "FLUCONAZOLE",
            severity: "severe",
            description: "Ức chế CYP3A4 làm kéo dài tác dụng Midazolam. An thần kéo dài - giảm liều Midazolam.",
        },
        {
            drugCodeA: "CLOMIPRAMIN",
            drugCodeB: "SERTRALINE",
            severity: "severe",
            description: "Cộng hợp tác dụng serotonin và ức chế chuyển hóa. Nguy cơ hội chứng serotonin - tránh phối hợp.",
        },
        {
            drugCodeA: "METHADON",
            drugCodeB: "AMIODARONHYDRO",
            severity: "severe",
            description: "Cộng hợp kéo dài khoảng QT. Nguy cơ xoắn đỉnh - theo dõi ECG định kỳ.",
        },
        {
            drugCodeA: "METHADON",
            drugCodeB: "DIAZEPAMUONG",
            severity: "severe",
            description: "Cộng hợp ức chế hô hấp. Nguy cơ tử vong do ngừng thở - tránh phối hợp.",
        },
        {
            drugCodeA: "NALOXONHYDROCL",
            drugCodeB: "MORPHINHYDROCL",
            severity: "severe",
            description: "Đối kháng cạnh tranh tại thụ thể opioid. Thuốc giải độc chuyên biệt; gây hội chứng cai cấp ở người phụ thuộc opioid.",
        },
        {
            drugCodeA: "LEVODOPACARBID",
            drugCodeB: "HALOPERIDOL",
            severity: "severe",
            description: "Thuốc chống loạn thần phong bế thụ thể dopamin, đối kháng Levodopa. Làm nặng triệu chứng Parkinson - tránh phối hợp.",
        },
        {
            drugCodeA: "LEVODOPACARBID",
            drugCodeB: "PYRIDOXINVITAM",
            severity: "moderate",
            description: "B6 liều cao tăng khử carboxyl Levodopa ngoại biên. Ít ý nghĩa khi có Carbidopa; tránh B6 liều rất cao.",
        },
        {
            drugCodeA: "LEVODOPACARBID",
            drugCodeB: "METOCLOPRAMID",
            severity: "severe",
            description: "Metoclopramid phong bế dopamin trung ương. Giảm hiệu quả điều trị và gây ngoại tháp - dùng Domperidon thay thế.",
        },
        {
            drugCodeA: "METF500",
            drugCodeB: "CIMETIDIN",
            severity: "moderate",
            description: "Cạnh tranh bài tiết ở ống thận làm tăng nồng độ Metformin. Theo dõi đường huyết và chức năng thận.",
        },
        {
            drugCodeA: "GLIBENCLAMID",
            drugCodeB: "BISOPROLOL",
            severity: "moderate",
            description: "Chẹn beta che lấp triệu chứng hạ đường huyết. Cảnh báo bệnh nhân, tăng tần suất tự theo dõi đường huyết.",
        },
        {
            drugCodeA: "GLIBENCLAMID",
            drugCodeB: "PREDNISOLONE",
            severity: "moderate",
            description: "Corticosteroid làm tăng đường huyết, đối kháng thuốc hạ đường huyết. Theo dõi đường huyết, có thể cần tăng liều thuốc hạ đường huyết.",
        },
        {
            drugCodeA: "ACARBOSE",
            drugCodeB: "METF500",
            severity: "mild",
            description: "Cộng hợp tác dụng hạ đường huyết và tác dụng phụ tiêu hóa. Phối hợp hợp lý về lâm sàng - tăng liều từ từ để giảm đầy hơi, tiêu chảy.",
        },
        {
            drugCodeA: "LEVOTHYROXINE",
            drugCodeB: "SATSULFATOXALA",
            severity: "moderate",
            description: "Sắt tạo phức làm giảm hấp thu Levothyroxin. Uống cách nhau ít nhất 4 giờ.",
        },
        {
            drugCodeA: "PROPYLTHIOURAC",
            drugCodeB: "WARFARIN",
            severity: "moderate",
            description: "Thay đổi chuyển hóa yếu tố đông máu khi trạng thái giáp thay đổi. Theo dõi INR khi điều chỉnh liều kháng giáp.",
        },
        {
            drugCodeA: "PREDNISOLONE",
            drugCodeB: "FUROSEMIDE",
            severity: "moderate",
            description: "Cộng hợp mất kali. Nguy cơ hạ kali máu - theo dõi điện giải.",
        },
        {
            drugCodeA: "HYDROCORTISONA",
            drugCodeB: "WARFARIN",
            severity: "moderate",
            description: "Corticosteroid có thể làm thay đổi đáp ứng chống đông. Theo dõi INR khi bắt đầu hoặc ngừng corticosteroid.",
        },
        {
            drugCodeA: "PANTOPRAZOL",
            drugCodeB: "CLOPIDOGREL",
            severity: "mild",
            description: "Ức chế CYP2C19 yếu hơn Omeprazol. Được coi là lựa chọn PPI an toàn hơn khi cần phối hợp.",
        },
        {
            drugCodeA: "MAGNESIHYDROXY",
            drugCodeB: "DOXYCYCLINE",
            severity: "moderate",
            description: "Tạo phức chelat làm giảm hấp thu Tetracyclin. Uống cách nhau ít nhất 2 giờ.",
        },
        {
            drugCodeA: "MAGNESIHYDROXY",
            drugCodeB: "DIGOXIN",
            severity: "moderate",
            description: "Antacid hấp phụ làm giảm hấp thu Digoxin. Uống cách nhau ít nhất 2 giờ.",
        },
        {
            drugCodeA: "METOCLOPRAMID",
            drugCodeB: "DOMPERIDONE",
            severity: "moderate",
            description: "Cộng hợp phong bế dopamin. Không phối hợp - tăng nguy cơ ngoại tháp mà không tăng hiệu quả.",
        },
        {
            drugCodeA: "CIMETIDIN",
            drugCodeB: "PHENYTOIN",
            severity: "severe",
            description: "Ức chế CYP làm giảm chuyển hóa Phenytoin. Tăng nguy cơ ngộ độc - theo dõi nồng độ; Famotidin ít tương tác hơn.",
        },
        {
            drugCodeA: "CIMETIDIN",
            drugCodeB: "THEOPHYLLINE",
            severity: "severe",
            description: "Ức chế CYP1A2 làm giảm chuyển hóa Theophyllin. Nguy cơ ngộ độc - giảm liều Theophyllin hoặc đổi sang Famotidin.",
        },
        {
            drugCodeA: "MUOIBISMUTH",
            drugCodeB: "DOXYCYCLINE",
            severity: "moderate",
            description: "Bismuth làm giảm hấp thu Tetracyclin. Uống cách nhau ít nhất 2 giờ.",
        },
        {
            drugCodeA: "METHOTREXAT",
            drugCodeB: "IBU400",
            severity: "severe",
            description: "NSAID giảm thải trừ Methotrexat qua thận. Nguy cơ suy tủy và độc tính nặng - tránh phối hợp, đặc biệt liều cao.",
        },
        {
            drugCodeA: "METHOTREXAT",
            drugCodeB: "CALCIFOLINAT",
            severity: "severe",
            description: "Folinat cạnh tranh phục hồi dự trữ folat nội bào. Dùng có chủ đích để giải cứu sau Methotrexat liều cao - tuân thủ thời điểm và liều.",
        },
        {
            drugCodeA: "METHOTREXAT",
            drugCodeB: "OMEP20",
            severity: "moderate",
            description: "PPI làm giảm thải trừ Methotrexat qua thận. Ngừng PPI quanh đợt Methotrexat liều cao.",
        },
        {
            drugCodeA: "MERCAPTOPURIN",
            drugCodeB: "ALLOPURINOL",
            severity: "severe",
            description: "Ức chế xanthin oxidase làm tăng nồng độ Mercaptopurin. Giảm liều Mercaptopurin còn 25-33% và theo dõi công thức máu.",
        },
        {
            drugCodeA: "CICLOSPORIN",
            drugCodeB: "ATORVASTATIN",
            severity: "severe",
            description: "Ức chế OATP1B1 và CYP3A4 làm tăng nồng độ statin. Nguy cơ tiêu cơ vân - giới hạn liều statin, theo dõi CK.",
        },
        {
            drugCodeA: "CICLOSPORIN",
            drugCodeB: "SPIRONOLACTONE",
            severity: "severe",
            description: "Cộng hợp giữ kali và độc tính thận. Nguy cơ tăng kali máu - theo dõi kali và creatinin.",
        },
        {
            drugCodeA: "CYCLOPHOSPHAMI",
            drugCodeB: "MESNA",
            severity: "mild",
            description: "Mesna liên kết acrolein trong nước tiểu. Phối hợp có chủ đích để dự phòng viêm bàng quang xuất huyết.",
        },
        {
            drugCodeA: "CISPLATIN",
            drugCodeB: "GENTAMICIN",
            severity: "severe",
            description: "Cộng hợp độc tính trên thận và thính giác. Tránh phối hợp; bù dịch đầy đủ, theo dõi creatinin và thính lực.",
        },
        {
            drugCodeA: "CISPLATIN",
            drugCodeB: "FUROSEMIDE",
            severity: "severe",
            description: "Cộng hợp độc tính trên tai và mất điện giải. Theo dõi thính lực, magnesi và kali máu.",
        },
        {
            drugCodeA: "DOXORUBICIN",
            drugCodeB: "CYCLOPHOSPHAMI",
            severity: "moderate",
            description: "Cộng hợp độc tính trên tim. Theo dõi chức năng thất trái, giới hạn liều tích lũy Doxorubicin.",
        },
        {
            drugCodeA: "TAMOXIFEN",
            drugCodeB: "FLUOXETINE",
            severity: "severe",
            description: "Ức chế CYP2D6 làm giảm chuyển hóa Tamoxifen thành endoxifen hoạt tính. Giảm hiệu quả điều trị ung thư vú - chọn SSRI khác như Sertralin liều thấp.",
        },
        {
            drugCodeA: "TAMOXIFEN",
            drugCodeB: "WARFARIN",
            severity: "severe",
            description: "Ức chế chuyển hóa Warfarin. Tăng nguy cơ xuất huyết - theo dõi INR chặt.",
        },
        {
            drugCodeA: "SUXAMETHONIUMC",
            drugCodeB: "NEOSTIGMIN",
            severity: "severe",
            description: "Neostigmin kéo dài phong bế khử cực giai đoạn I. Không dùng để hóa giải Suxamethonium - theo dõi hô hấp.",
        },
        {
            drugCodeA: "VECURONIUMBROM",
            drugCodeB: "NEOSTIGMIN",
            severity: "mild",
            description: "Neostigmin hóa giải phong bế không khử cực. Phối hợp có chủ đích khi kết thúc gây mê; dùng kèm Atropin để giảm tác dụng muscarinic.",
        },
        {
            drugCodeA: "VECURONIUMBROM",
            drugCodeB: "MAGNESISULFAT",
            severity: "severe",
            description: "Magnesi tăng cường phong bế thần kinh cơ. Kéo dài liệt cơ - giảm liều giãn cơ, theo dõi TOF.",
        },
        {
            drugCodeA: "NEOSTIGMIN",
            drugCodeB: "ATROPINSULFAT",
            severity: "mild",
            description: "Atropin đối kháng tác dụng muscarinic của Neostigmin. Phối hợp tiêu chuẩn để tránh nhịp chậm và tăng tiết.",
        },
        {
            drugCodeA: "KETAMINHYDROCL",
            drugCodeB: "THEOPHYLLINE",
            severity: "moderate",
            description: "Cộng hợp hạ ngưỡng co giật. Tăng nguy cơ co giật - thận trọng khi phối hợp.",
        },
        {
            drugCodeA: "HALOTHAN",
            drugCodeB: "EPINEPHRINTART",
            severity: "severe",
            description: "Halothan làm cơ tim nhạy cảm với catecholamin. Nguy cơ loạn nhịp thất - hạn chế liều Adrenalin tối đa.",
        },
        {
            drugCodeA: "ALLOPURINOL",
            drugCodeB: "WARFARIN",
            severity: "moderate",
            description: "Ức chế chuyển hóa Warfarin. Theo dõi INR khi bắt đầu Allopurinol.",
        },
        {
            drugCodeA: "COLCHICINE",
            drugCodeB: "ATORVASTATIN",
            severity: "severe",
            description: "Cộng hợp độc tính trên cơ. Nguy cơ bệnh cơ, tiêu cơ vân - theo dõi CK và triệu chứng đau cơ.",
        },
        {
            drugCodeA: "ACIDTRANEXAMIC",
            drugCodeB: "ETHINYLESTRADI",
            severity: "severe",
            description: "Cộng hợp làm tăng nguy cơ huyết khối. Tránh phối hợp ở người có yếu tố nguy cơ huyết khối.",
        },
        {
            drugCodeA: "ACIDTRANEXAMIC",
            drugCodeB: "HEPARINNATRI",
            severity: "severe",
            description: "Đối kháng dược lực học trực tiếp. Chỉ dùng khi có chỉ định đảo ngược chống đông, cân nhắc nguy cơ huyết khối.",
        },
        {
            drugCodeA: "OXYTOCIN",
            drugCodeB: "MISOPROSTOL",
            severity: "moderate",
            description: "Cộng hợp kích thích co bóp tử cung. Nguy cơ tăng trương lực/vỡ tử cung - không dùng đồng thời trong khởi phát chuyển dạ.",
        },
        {
            drugCodeA: "ERGOMETRINMALE",
            drugCodeB: "AMLO5",
            severity: "moderate",
            description: "Ergometrin gây co mạch, đối kháng thuốc hạ áp. Theo dõi huyết áp; thận trọng ở bệnh nhân tăng huyết áp.",
        },
        {
            drugCodeA: "TIMOLOL",
            drugCodeB: "BISOPROLOL",
            severity: "severe",
            description: "Timolol nhỏ mắt hấp thu toàn thân cộng hợp với chẹn beta uống. Nguy cơ nhịp chậm, co thắt phế quản - theo dõi mạch, tránh ở bệnh nhân hen.",
        },
        {
            drugCodeA: "ACETAZOLAMID",
            drugCodeB: "ASP81",
            severity: "severe",
            description: "Salicylat đẩy Acetazolamid khỏi protein và làm giảm thải trừ. Nguy cơ ngộ độc Acetazolamid, toan chuyển hóa - tránh liều cao Aspirin.",
        },
        {
            drugCodeA: "KALICLORID",
            drugCodeB: "SPIRONOLACTONE",
            severity: "severe",
            description: "Cộng hợp làm tăng kali máu. Tránh phối hợp trừ khi có hạ kali máu chứng minh; theo dõi điện giải.",
        },
        {
            drugCodeA: "FUROSEMIDE",
            drugCodeB: "IBU400",
            severity: "moderate",
            description: "NSAID giảm prostaglandin thận, đối kháng tác dụng lợi tiểu. Giảm hiệu quả lợi tiểu và nguy cơ suy thận - theo dõi cân nặng, creatinin.",
        },
        {
            drugCodeA: "SALB100",
            drugCodeB: "BISOPROLOL",
            severity: "severe",
            description: "Chẹn beta đối kháng tác dụng giãn phế quản. Nguy cơ co thắt phế quản - tránh chẹn beta không chọn lọc ở bệnh nhân hen.",
        },
        {
            drugCodeA: "THEOPHYLLINE",
            drugCodeB: "PHENYTOIN",
            severity: "moderate",
            description: "Cảm ứng enzym làm giảm nồng độ cả hai thuốc. Theo dõi nồng độ cả hai thuốc.",
        },
        {
            drugCodeA: "THANHOAT",
            drugCodeB: "PARA500",
            severity: "moderate",
            description: "Than hoạt hấp phụ thuốc trong đường tiêu hóa. Trong ngộ độc là tác dụng mong muốn; tránh dùng chung với thuốc uống thông thường.",
        },
        {
            drugCodeA: "CAFEINCITRAT",
            drugCodeB: "THEOPHYLLINE",
            severity: "moderate",
            description: "Cộng hợp tác dụng kích thích và độc tính methylxanthin. Không phối hợp - nguy cơ nhịp nhanh, kích thích ở trẻ sinh non.",
        },
    ];

    for (const i of interactions) {
        const drugIdA = drugMap.get(i.drugCodeA);
        const drugIdB = drugMap.get(i.drugCodeB);
        if (!drugIdA || !drugIdB) continue;

        await prisma.drugInteraction.upsert({
            where: { drugIdA_drugIdB: { drugIdA, drugIdB } },
            update: { severity: i.severity, description: i.description, isActive: true },
            create: {
                drugIdA,
                drugIdB,
                severity: i.severity,
                description: i.description,
                isActive: true,
            },
        });
    }

    const count = await prisma.drugInteraction.count();
    console.log(`Seeded drug interactions, total in DB: ${count}`);
}
